/*
Copyright (c) 2017 AscEmu Team <http://www.ascemu.org/>
This file is released under the MIT license. See README-MIT for more information.
*/

#pragma once

enum SpellEffectTarget
{
    EFF_TARGET_NONE                                               = 0,
    EFF_TARGET_SELF                                               = 1,
    EFF_TARGET_RANDOM_ENEMY_CHAIN_IN_AREA                         = 2,
    EFF_TARGET_RANDOM_FRIENDLY_CHAIN_IN_AREA                      = 3,
    EFF_TARGET_RANDOM_UNIT_CHAIN_IN_AREA                          = 4,
    EFF_TARGET_PET                                                = 5,
    EFF_TARGET_CHAIN_DAMAGE                                       = 6,
    EFF_TARGET_AREAEFFECT_INSTANT                                 = 7,
    EFF_TARGET_AREAEFFECT_CUSTOM                                  = 8, // not sure of the correct name
    EFF_TARGET_HEARTSTONE_LOCATION                                = 9,
    EFF_TARGET_11                                                 = 11, // used by spell id 4
    EFF_TARGET_ALL_ENEMY_IN_AREA                                  = 15,
    EFF_TARGET_ALL_ENEMY_IN_AREA_INSTANT                          = 16,
    EFF_TARGET_TELEPORT_LOCATION                                  = 17,
    EFF_TARGET_LOCATION_TO_SUMMON                                 = 18,
    EFF_TARGET_ALL_PARTY_AROUND_CASTER                            = 20,
    EFF_TARGET_SINGLE_FRIEND                                      = 21,
    EFF_TARGET_22                                                 = 22, // Caster coordinates in TargetA but target selection dependent in TargetB
    EFF_TARGET_GAMEOBJECT                                         = 23,
    EFF_TARGET_IN_FRONT_OF_CASTER                                 = 24,
    EFF_TARGET_DUEL                                               = 25,
    EFF_TARGET_GAMEOBJECT_ITEM                                    = 26,
    EFF_TARGET_PET_MASTER                                         = 27,
    EFF_TARGET_ALL_ENEMY_IN_AREA_CHANNELED                        = 28,
    EFF_TARGET_ALL_PARTY_IN_AREA_CHANNELED                        = 29,
    EFF_TARGET_ALL_FRIENDLY_AROUND_CASTER                         = 30,
    EFF_TARGET_ALL_FRIENDLY_IN_AREA                               = 31,
    EFF_TARGET_MINION                                             = 32,
    EFF_TARGET_ALL_PARTY                                          = 33,
    EFF_TARGET_ALL_PARTY_AROUND_CASTER_2                          = 34,
    EFF_TARGET_SINGLE_PARTY                                       = 35,
    EFF_TARGET_ALL_ENEMY_AROUND_CASTER                            = 36,
    EFF_TARGET_ALL_PARTY_2                                        = 37,
    EFF_TARGET_SCRIPTED_OR_SINGLE_TARGET                          = 38,
    EFF_TARGET_SELF_FISHING                                       = 39,
    EFF_TARGET_SCRIPTED_GAMEOBJECT                                = 40,
    EFF_TARGET_TOTEM_EARTH                                        = 41,
    EFF_TARGET_TOTEM_WATER                                        = 42,
    EFF_TARGET_TOTEM_AIR                                          = 43,
    EFF_TARGET_TOTEM_FIRE                                         = 44,
    EFF_TARGET_CHAIN_HEAL                                         = 45,
    EFF_TARGET_SCIPTED_OBJECT_LOCATION                            = 46,
    EFF_TARGET_DYNAMIC_OBJECT_FRONT                               = 47,
    EFF_TARGET_DYNAMIC_OBJECT_BEHIND                              = 48,
    EFF_TARGET_DYNAMIC_OBJECT_LEFT                                = 49,
    EFF_TARGET_DYNAMIC_OBJECT_RIGHT                               = 50,
    EFF_TARGET_AOE_GAMEOBJECT_AROUND_CASTER                       = 51,
    EFF_TARGET_AOE_GAMEOBJECT_AROUND_DESTINATION                  = 52,
    EFF_TARGET_CURRENT_ENEMY_TARGET_COORDINATES                   = 53,
    EFF_TARGET_FRONTAL_CONE_LARGE                                 = 54,
    EFF_TARGET_LOCATION_INFRONT_CASTER                            = 55,
    EFF_TARGET_ALL_RAID                                           = 56,
    EFF_TARGET_SINGLE_FRIEND_2                                    = 57,
    EFF_TARGET_58                                                 = 58,
    EFF_TARGET_FRONTAL_CONE_FRIENDLY                              = 59,
    EFF_TARGET_FRONTAL_CONE_NARROW                                = 60,
    EFF_TARGET_AREAEFFECT_PARTY_AND_CLASS                         = 61,
    EFF_TARGET_DUEL_COORDINATES                                   = 63,
    EFF_TARGET_VICTIM_FRONTAL                                     = 64,
    EFF_TARGET_VICTIM_BEHIND                                      = 65,
    EFF_TARGET_VICTIM_RIGHT                                       = 66,
    EFF_TARGET_VICTIM_LEFT                                        = 67,
    EFF_TARGET_68                                                 = 68,
    EFF_TARGET_69                                                 = 69,
    EFF_TARGET_70                                                 = 70,
    EFF_TARGET_RANDOM_NEARBY_SUMMON_LOCATION                      = 72,
    EFF_TARGET_RANDOM_CIRCUMFERENCE_SUMMON_LOCATION_AROUND_CASTER = 73,
    EFF_TARGET_74                                                 = 74,
    EFF_TARGET_RANDOM_CIRCUMFERENCE_SUMMON_LOCATION_AROUND_TARGET = 75,
    EFF_TARGET_DYNAMIC_OBJECT_COORDINATES                         = 76,
    EFF_TARGET_SINGLE_ENEMY                                       = 77,
    EFF_TARGET_POINT_AT_NORTH                                     = 78,
    EFF_TARGET_POINT_AT_SOUTH                                     = 79,
    EFF_TARGET_POINT_AT_EAST                                      = 80,
    EFF_TARGET_POINT_AT_WEST                                      = 81,
    EFF_TARGET_POINT_AT_NE                                        = 82,
    EFF_TARGET_POINT_AT_NW                                        = 83,
    EFF_TARGET_POINT_AT_SE                                        = 84,
    EFF_TARGET_POINT_AT_SW                                        = 85,
    EFF_TARGET_RANDOM_NEARBY_DESTINATION                          = 86,
    EFF_TARGET_SELF_2                                             = 87,
    EFF_TARGET_88                                                 = 88,
    EFF_TARGET_DIRECT_FORWARD                                     = 89,
    EFF_TARGET_NON_COMBAT_PET                                     = 90,
    EFF_TARGET_91                                                 = 91,
    EFF_TARGET_SUMMONER                                           = 92,
    EFF_TARGET_CONTROLLED_VEHICLE                                 = 94,
    EFF_TARGET_VEHICLE_DRIVER                                     = 95,
    EFF_TARGET_VEHICLE_PASSENGER_0                                = 96,
    EFF_TARGET_VEHICLE_PASSENGER_1                                = 97,
    EFF_TARGET_VEHICLE_PASSENGER_2                                = 98,
    EFF_TARGET_VEHICLE_PASSENGER_3                                = 99,
    EFF_TARGET_VEHICLE_PASSENGER_4                                = 100,
    EFF_TARGET_VEHICLE_PASSENGER_5                                = 101,
    EFF_TARGET_VEHICLE_PASSENGER_6                                = 102,
    EFF_TARGET_VEHICLE_PASSENGER_7                                = 103,
    EFF_TARGET_IN_FRONT_OF_CASTER_30_DEGREE                       = 104,
    EFF_TARGET_105                                                = 105,
    EFF_TARGET_106                                                = 106,
    EFF_TARGET_GAMEOBJECT_IN_FRONT_OF_CASTER_90_DEGREE            = 108,
    EFF_TARGET_FRONTAL_CONE_NARROW_2                              = 110,
    // these are custom, feel free to move them further if targeting gets extended
    EFF_TARGET_CUSTOM_PARTY_INJURED_SINGLE                        = 120,
    EFF_TARGET_CUSTOM_PARTY_INJURED_MULTI                         = 121,
    EFF_TARGET_CONE_IN_FRONT                                      = 122,
    EFF_TARGET_LIST_LENGTH_MARKER                                 = 123,
};
