# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install deps
          command: |
            apt-get update && apt-get install -y zlib1g-dev
            apt-get update && apt-get install -y libssl-dev
            apt-get update && apt-get install -y libpcre3-dev
            apt-get update && apt-get install -y libbz2-dev
            apt-get update && apt-get install -y default-libmysqlclient-dev
            apt-get update && apt-get install -y libmysql++-dev
      - run:
          name: Check versions
          command: |
            cmake --version
      - run:
          name: Setup
          command: |
            mkdir ascemu_classic
            cd ascemu_classic
            cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DUSE_PCH=1 -DASCEMU_VERSION=Classic
            cd ..
            mkdir ascemu_bc
            cd ascemu_bc
            cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DUSE_PCH=1 -DASCEMU_VERSION=TBC
            cd ..
            mkdir ascemu_wotlk
            cd ascemu_wotlk
            cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DUSE_PCH=1 -DASCEMU_VERSION=WotLK
            cd ..
            mkdir ascemu_cata
            cd ascemu_cata
            cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DUSE_PCH=1 -DASCEMU_VERSION=Cata
            cd ..
            mkdir ascemu_mop
            cd ascemu_mop
            cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DUSE_PCH=1 -DASCEMU_VERSION=Mop
            cd ..
      - run:
          name: Build Classic
          command: |
            cd ascemu_classic
            make -j 4
            cd ..
      - run:
          name: Build TBC
          command: |
            cd ascemu_bc
            make -j 4
            cd ..
      - run:
          name: Build WotLK
          command: |
            cd ascemu_wotlk
            make -j 4
            cd ..
      - run:
          name: Build Cata
          command: |
            cd ascemu_cata
            make -j 4
            cd ..
      - run:
          name: Build Mop
          command: |
            cd ascemu_mop
            make -j 4
            cd ..